# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_ID', models.CharField(max_length=10)),
                ('exp_name', models.CharField(max_length=150)),
                ('exp_description', models.CharField(max_length=150)),
                ('exp_createtime', models.DateTimeField()),
                ('exp_updatetime', models.DateTimeField()),
                ('exp_owner', models.CharField(max_length=150)),
                ('exp_images', models.CharField(max_length=150)),
                ('exp_network', models.CharField(max_length=150)),
                ('exp_guide', models.CharField(max_length=150)),
                ('exp_result', models.CharField(max_length=150)),
                ('exp_reportDIR', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
