# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-25 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0003_auto_20161213_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_id', models.CharField(max_length=10)),
                ('exp_name', models.CharField(max_length=150)),
                ('exp_description', models.TextField(null=True)),
                ('exp_createtime', models.DateTimeField(auto_now_add=True)),
                ('exp_updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('exp_network', models.CharField(max_length=150)),
                ('exp_guide', models.TextField(null=True)),
                ('exp_result', models.CharField(max_length=150, null=True)),
                ('exp_reportDIR', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('exp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExpInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expInstance_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('servers', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User')),
                ('sourceExpTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExpNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('exp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_id', models.CharField(max_length=50)),
                ('network_name', models.CharField(max_length=100)),
                ('network_description', models.TextField(null=True)),
                ('subnet_name', models.CharField(max_length=100)),
                ('gateway_ip', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VMImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=255)),
                ('is_public', models.CharField(default='NO', max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('size', models.BigIntegerField()),
                ('min_disk', models.IntegerField()),
                ('min_ram', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User')),
                ('tags', models.ManyToManyField(to='Iserlab.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='VMInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('createtime', models.DateTimeField()),
                ('updatetime', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20, null=True)),
                ('vncurl', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='expnetwork',
            name='network_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Network'),
        ),
        migrations.AddField(
            model_name='expimage',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.VMImage'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='exp_images',
            field=models.ManyToManyField(to='Iserlab.VMImage'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='exp_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='exp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Experiment'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='stu_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Student'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='teacher_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User'),
        ),
    ]
