# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-25 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0004_auto_20161225_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='exp_network',
        ),
        migrations.AddField(
            model_name='experiment',
            name='exp_network',
            field=models.ManyToManyField(to='Iserlab.Network'),
        ),
    ]
