# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-25 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0007_auto_20161225_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='exp_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='stu_username',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='teacher_username',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='exp_images',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='exp_network',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='exp_owner',
        ),
        migrations.RemoveField(
            model_name='expimage',
            name='exp_id',
        ),
        migrations.RemoveField(
            model_name='expimage',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='expinstance',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='expinstance',
            name='sourceExpTemplate',
        ),
        migrations.RemoveField(
            model_name='expnetwork',
            name='exp_id',
        ),
        migrations.RemoveField(
            model_name='expnetwork',
            name='network_id',
        ),
        migrations.RemoveField(
            model_name='vmimage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vmimage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='vminstance',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Experiment',
        ),
        migrations.DeleteModel(
            name='ExpImage',
        ),
        migrations.DeleteModel(
            name='ExpInstance',
        ),
        migrations.DeleteModel(
            name='ExpNetwork',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='VMImage',
        ),
        migrations.DeleteModel(
            name='VMInstance',
        ),
    ]
