# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-25 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0009_auto_20161225_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expinstance',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vmimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
