# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-25 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0010_auto_20161225_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expimage',
            name='exp_id',
        ),
        migrations.RemoveField(
            model_name='expimage',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='expnetwork',
            name='exp_id',
        ),
        migrations.RemoveField(
            model_name='expnetwork',
            name='network_id',
        ),
        migrations.AlterField(
            model_name='vmimage',
            name='min_disk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vmimage',
            name='min_ram',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vmimage',
            name='status',
            field=models.CharField(default='active', max_length=30),
        ),
        migrations.DeleteModel(
            name='ExpImage',
        ),
        migrations.DeleteModel(
            name='ExpNetwork',
        ),
    ]
