# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-26 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0011_auto_20161225_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createtime'],
            },
        ),
        migrations.CreateModel(
            name='NetworkCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('network_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Network')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User')),
            ],
            options={
                'ordering': ['-createtime'],
            },
        ),
        migrations.AddField(
            model_name='vmimage',
            name='own_project',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='imagecart',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.VMImage'),
        ),
        migrations.AddField(
            model_name='imagecart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User'),
        ),
    ]
