# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0012_auto_20161226_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='subnet_name',
        ),
        migrations.AddField(
            model_name='network',
            name='subnet_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
