# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0014_auto_20161227_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User'),
        ),
        migrations.AddField(
            model_name='network',
            name='shared',
            field=models.CharField(default='False', max_length=10, null=True),
        ),
    ]
