# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-27 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0016_experiment_exp_image_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='shared',
            new_name='is_shared',
        ),
        migrations.AddField(
            model_name='experiment',
            name='is_shared',
            field=models.CharField(default='False', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='shared_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='shared_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vmimage',
            name='is_shared',
            field=models.CharField(default='False', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vmimage',
            name='shared_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vmimage',
            name='is_public',
            field=models.CharField(default='YES', max_length=10),
        ),
    ]
