# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0018_auto_20161230_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmimage',
            name='flavor',
            field=models.CharField(blank=True, default='m1.tiny', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vmimage',
            name='keypair',
            field=models.CharField(blank=True, default='mykey', max_length=20, null=True),
        ),
    ]
