# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0019_auto_20161230_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='subnet_id',
            new_name='subnet_name',
        ),
    ]
