# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0020_auto_20161230_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vmimage',
            name='image_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
