# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0021_auto_20161230_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='subnet_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
