# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0022_network_subnet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='allocation_pools_end',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='allocation_pools_start',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='enable_dhcp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
