# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0025_auto_20170103_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
