# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0027_auto_20170103_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='expinstance',
            name='creator',
            field=models.CharField(default='mcy', max_length=20),
            preserve_default=False,
        ),
    ]
