# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-01 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0028_expinstance_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expinstance',
            name='creator',
            field=models.CharField(max_length=201),
        ),
    ]
