# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-02 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0029_auto_20170301_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='stop_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
