# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-02 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0030_auto_20170302_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='stop_time',
        ),
    ]
