# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-02 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0031_auto_20170302_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='stop_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vminstance',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
