# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-06 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0036_auto_20170303_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Experiment')),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Student')),
            ],
        ),
    ]
