# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-06 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0037_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
