# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-06 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0039_auto_20170306_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='average_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='doing_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='done_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='total_stu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='undo_count',
            field=models.IntegerField(default=0),
        ),
    ]
