# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-06 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0042_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='socre_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
