# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-06 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0044_auto_20170306_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='socre_time',
            new_name='score_time',
        ),
    ]
