# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0047_auto_20170306_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
