# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0049_auto_20170307_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='stu',
            new_name='group',
        ),
    ]
