# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0050_auto_20170307_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='finishedTime',
            new_name='createTime',
        ),
    ]
