# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0051_auto_20170307_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='finishedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
