# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0052_auto_20170307_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='situation',
            field=models.CharField(default='undo', max_length=10),
        ),
    ]
