# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0053_auto_20170307_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='delivery_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
