# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0055_score_starttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score_time',
            new_name='scoreTime',
        ),
    ]
