# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-08 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0058_auto_20170308_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='end_time',
            new_name='stop_time',
        ),
    ]
