# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0061_auto_20170309_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecart',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='networkcart',
            old_name='network_id',
            new_name='network',
        ),
    ]
