# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0062_auto_20170310_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmimage',
            name='path',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
