# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-12 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0064_auto_20170310_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmimage',
            name='path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
