# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-13 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0065_auto_20170312_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='enable_dhcp',
            field=models.BooleanField(default=True),
        ),
    ]
