# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-13 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0066_auto_20170313_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='exp_guide_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='report_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
