# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-13 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0067_auto_20170313_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='exp_description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
