# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-14 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0068_auto_20170313_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='group',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Group'),
            preserve_default=False,
        ),
    ]
