# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0070_auto_20170314_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='dns',
            field=models.CharField(blank=True, default='10.21.1.205', max_length=30, null=True),
        ),
    ]
