# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0071_network_dns'),
    ]

    operations = [
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flavor', models.CharField(blank=True, default='m1.tiny', max_length=10, null=True)),
                ('keypair', models.CharField(blank=True, default='mykey', max_length=20, null=True)),
                ('security_group', models.CharField(blank=True, default='default', max_length=30, null=True)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Experiment')),
            ],
        ),
        migrations.RemoveField(
            model_name='vminstance',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='expinstance',
            name='expInstance_id',
        ),
        migrations.RemoveField(
            model_name='vmimage',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='vmimage',
            name='keypair',
        ),
        migrations.DeleteModel(
            name='VMInstance',
        ),
        migrations.AddField(
            model_name='vm',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.VMImage'),
        ),
        migrations.AddField(
            model_name='vm',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Network'),
        ),
    ]
