# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0072_auto_20170316_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=20)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('vncurl', models.URLField()),
                ('exp_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.ExpInstance')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.VM')),
            ],
            options={
                'ordering': ['-createtime'],
            },
        ),
    ]
