# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0073_vminstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expinstance',
            name='sourceExpTemplate',
        ),
        migrations.AlterField(
            model_name='vminstance',
            name='exp_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Score'),
        ),
        migrations.DeleteModel(
            name='ExpInstance',
        ),
    ]
