# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0077_remove_score_reporturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='VM_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='exp_image_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
