# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0078_auto_20170316_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vm',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User'),
        ),
    ]
