# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0079_auto_20170316_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
