# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0080_auto_20170316_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vm',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='experiment',
            name='VM_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
