# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0081_auto_20170316_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='VM_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
