# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-19 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0083_tempexp_tempgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempexp',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tempgroup',
            name='owner',
        ),
        migrations.DeleteModel(
            name='TempExp',
        ),
        migrations.DeleteModel(
            name='TempGroup',
        ),
    ]
