# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-19 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0085_tempexp_tempgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('network_id', models.CharField(blank=True, max_length=50, null=True)),
                ('subnet_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tenant_id', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User')),
            ],
            options={
                'ordering': ['-createtime'],
            },
        ),
        migrations.RemoveField(
            model_name='network',
            name='network_id',
        ),
        migrations.RemoveField(
            model_name='network',
            name='subnet_id',
        ),
        migrations.RemoveField(
            model_name='network',
            name='tenant_id',
        ),
        migrations.AlterField(
            model_name='vminstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User'),
        ),
        migrations.AlterField(
            model_name='vminstance',
            name='vncurl',
            field=models.URLField(null=True),
        ),
    ]
