# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-19 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0086_auto_20170319_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkinstance',
            name='owner',
        ),
        migrations.AlterField(
            model_name='vminstance',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='NetworkInstance',
        ),
    ]
