# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-19 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0088_networkinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vminstance',
            name='exp_instance',
        ),
        migrations.RemoveField(
            model_name='vminstance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vminstance',
            name='vm',
        ),
        migrations.DeleteModel(
            name='VMInstance',
        ),
    ]
