# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-20 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0094_auto_20170320_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinstance',
            name='allocation_pools_end',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='networkinstance',
            name='allocation_pools_start',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='networkinstance',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
