# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0097_auto_20170321_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routerinstance',
            name='gateway_ip_address',
        ),
        migrations.RemoveField(
            model_name='routerinstance',
            name='gateway_net_id',
        ),
        migrations.RemoveField(
            model_name='routerinstance',
            name='gateway_subnet_id',
        ),
    ]
