# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0098_auto_20170321_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkinstance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vminstance',
            name='owner',
        ),
        migrations.AddField(
            model_name='networkinstance',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vminstance',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
