# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-30 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0099_auto_20170321_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='vminstance',
            name='result_image',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
