# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-22 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0100_auto_20170330_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='exp_guide',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='exp_reportDIR',
        ),
    ]
