# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-23 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0102_remove_experiment_exp_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='exp_instance', max_length=100)),
                ('owner_name', models.CharField(max_length=50)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('instance_status', models.CharField(blank=True, default='UNLAUNCHED', max_length=20, null=True)),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Experiment')),
            ],
            options={
                'ordering': ['-createtime'],
            },
        ),
        migrations.RemoveField(
            model_name='networkinstance',
            name='exp_instance',
        ),
        migrations.RemoveField(
            model_name='score',
            name='instance_status',
        ),
        migrations.RemoveField(
            model_name='score',
            name='result',
        ),
        migrations.RemoveField(
            model_name='vminstance',
            name='exp_instance',
        ),
        migrations.AddField(
            model_name='networkinstance',
            name='belong_exp_instance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='exp_instance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='result_exp_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vminstance',
            name='belong_exp_instance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
