# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-23 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0104_auto_20170423_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vmimage',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
