# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0106_expinstance_score_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminstance',
            name='connetc_net',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Iserlab.NetworkInstance'),
        ),
        migrations.AlterField(
            model_name='expinstance',
            name='instance_status',
            field=models.CharField(blank=True, default='UNCHEDED', max_length=20, null=True),
        ),
    ]
