# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0108_auto_20170424_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vminstance',
            old_name='connetc_net',
            new_name='connect_net',
        ),
    ]
