# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0109_auto_20170424_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmimage',
            name='os',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
