# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0110_vmimage_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmimage',
            name='disk_format',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
