# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0111_vmimage_disk_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmimage',
            name='disk_format',
            field=models.CharField(default='QCOW2', max_length=20),
        ),
    ]
