# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0112_auto_20170424_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vm',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='exp_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User'),
        ),
    ]
