# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0113_auto_20170424_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='owner',
        ),
    ]
