# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0118_auto_20170425_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempexp',
            name='exp_owner_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
