# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0119_tempexp_exp_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempexp',
            name='exp_owner',
        ),
    ]
