# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0120_remove_tempexp_exp_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='stuCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tempgroup',
            name='stuCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
