# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0122_mytempexp_mytempgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempexp',
            name='exp_images',
        ),
        migrations.RemoveField(
            model_name='tempexp',
            name='exp_network',
        ),
        migrations.RemoveField(
            model_name='tempgroup',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tempgroup',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='TempExp',
        ),
        migrations.DeleteModel(
            name='TempGroup',
        ),
    ]
