# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-06 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0124_auto_20170425_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expinstance',
            name='instance_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Iserlab.Experiment'),
        ),
    ]
