# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-07 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0125_auto_20170506_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmimage',
            name='disk_format',
            field=models.CharField(default='qcow2', max_length=20),
        ),
    ]
