# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-07 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0126_auto_20170507_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTempImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.VMImage')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User')),
            ],
            options={
                'ordering': ['-createtime'],
            },
        ),
    ]
