# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-07 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0128_mytempnetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='operate_vm_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expinstance',
            name='operate_vminstance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
