# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-10 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0129_auto_20170507_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTempVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.User')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Iserlab.VM')),
            ],
            options={
                'ordering': ['-createtime'],
            },
        ),
    ]
