# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-17 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0130_mytempvm'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='is_opeareVM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vminstance',
            name='is_opeareVMInstance',
            field=models.BooleanField(default=False),
        ),
    ]
