# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-17 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0132_remove_vminstance_is_opearevminstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vm',
            old_name='is_opeareVM',
            new_name='is_operateVM',
        ),
    ]
