# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-31 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iserlab', '0133_auto_20170517_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
