# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=256, null=True, verbose_name='Writer'),
        ),
    ]
