# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-25 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20161225_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author2',
            name='headshot',
        ),
        migrations.RemoveField(
            model_name='author2',
            name='salutation',
        ),
        migrations.AlterField(
            model_name='author2',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
