# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-25 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20161225_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='author2',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
