# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-25 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_author2_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author2',
            name='address',
        ),
    ]
